MODEL:
  N_bag:
  - 1
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  agg_func: weight
  atom_bag_percent:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1
  ignore_warning: true
  random_seed: 1
  replace_flag: true
  select_atom_percent: 0
  signal_bag_percent:
  - 0.6
  - 0.8
  - 1
  - 1.2
  - 1.4
  - 1.6
TEST:
  cv_num: 5
  m: 20
  model: BOMP
  n: 600
  noise_levels:
  - 0.12
  - 0.14
  - 0.16
  - 0.18
  - 0.2
  p: 1000
  trial_num: 20
hydra:
  hydra_logging: hydra/hydra_logging.yaml
  job_logging: hydra/job_logging.yaml
  run:
    dir: memory/20230713/
