TEST:
  n: 600
  p: 1000
  m: 20
  noise_level: [0.12, 0.14, 0.16, 0.18, 0.2]
  model: BOMP
  cv_num: 5
  trial_num: 20
MODEL:
  N_bag: [1, 50, 100, 200, 300, 400, 500]
  signal_bag_percent: [0.6, 0.7, 0.8, 0.9, 1]
  atom_bag_percent: [0.5, 0.6, 0.7, 0.8, 0.9, 1]
  select_atom_percent: 0
  replace_flag: False
  agg_func: 'weight'
  K_start: 1
  K_end: 101
  K_step: 5
  ignore_warning: True
  random_seed: 1



