TEST:
  n: 600
  p: 1000
  m: 20
  noise_level: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
  model: BOMP
  cv_num: 5
  trial_num: 5
MODEL:
  N_bag: [10, 25, 50, 70]
  signal_bag_percent: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]
  atom_bag_percent: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]
  select_atom_percent: [0, 0.1, 0.3,0.5]
  replace_flag: True
  agg_func: 'weight'
  K_start: 1
  K_end: 41
  K_step: 4
  ignore_warning: True
  random_seed: 1


