TEST:
  n: 600
  p: 1000
  m: 20
  noise_level: [0, 0.05]
  model: BOMP
  cv_num: 5
  trial_num: 10
MODEL:
  N_bag: 10
  signal_bag_percent: [0, 0.9, 1]
  atom_bag_percent: 0.7
  select_atom_percent: 0
  replace_flag: False
  agg_func: 'weight'
  K_start: 1
  K_end: 41
  K_step: 1
  ignore_warning: True
  random_seed: 1


