N: 100000
d: 300
hydra:
  hydra_logging:
    level: CRITICAL
  job_logging:
    level: CRITICAL
  run:
    dir: ./outputs
noise_level_list:
- 0
- 0.01
- 0.05
- 0.1
output_dir: output
trial_num: 100
true_sparsity_list:
- 100
- 200
