TEST:
  n: 300
  p: 600
  m: 20
  noise_level: [0.2]
  model: BMP
  cv_num: 5
  trial_num: 4
MODEL:
  N_bag: 500
  signal_bag_percent: 0.8
  atom_bag_percent: 0.3
  select_atom_percent: 0
  replace_flag: False
  agg_func: 'weight'
  K_start: 1
  K_end: 11
  K_step: 2
  ignore_warning: True
  random_seed: null