MODEL:
  method: 'MP'
  bagging_sub_mum: 20
  # nomally depth will be 2*m(true_sparsity)
  depth: 50
  signal_bag_flag: True
  signal_bag_percent: 0.7
  atom_bag_percent: 0.7
  select_atom_percent: 0
  replace_flag: True 
  agg_func: 'weight'

TEST:
  trial_num: 10
  N: 100000
  d: 300
  true_sparsity: 25
  noise_level:
  - 0
  - 0.01
  - 0.05
  - 0.1

# hydra:
#   hydra_logging:
#     level: CRITICAL
#   job_logging:
#     level: CRITICAL
#   run:
#     dir: ./outputs