MODEL:
  method: 'BMP'
  bagging_sub_num: 10
  # nomally depth will be 2*m(true_sparsity)
  depth: 20
  signal_bag_flag: True
  signal_bag_percent: 0.7
  atom_bag_percent: 0.7
  select_atom_percent: 0
  replace_flag: True 
  agg_func: 'weight'

TEST:
  trial_num: 1
  N: 100000
  d: 300
  true_sparsity: 2
  noise_level:
  - 0


# hydra:
#   hydra_logging:
#     level: CRITICAL
#   job_logging:
#     level: CRITICAL
#   run:
#     dir: ./outputs