MODEL:
  agg_func: weight
  atom_bag_percent: 0.7
  method: MP
  replace_flag: true
  select_atom_percent: 0
  signal_bag_flag: true
  signal_bag_percent: 0.7
TEST:
  N: 100000
  d: 300
  noise_level_list:
  - 0
  - 0.01
  - 0.05
  - 0.1
  output_dir: output
  trial_num: 100
  true_sparsity_list:
  - 2
  - 5
  - 10
hydra:
  hydra_logging:
    level: CRITICAL
  job_logging:
    level: CRITICAL
  run:
    dir: ./outputs
