MODEL:
  Bag_lst:
  - 1
  - 50
  K_lst:
  - 10
  agg_func: weight
  atom_bag_percent:
  - 0.1
  - 0.2
  ignore_warning: true
  random_seed: 1
  replace_flag: false
  select_atom_percent: 0
  signal_bag_percent:
  - 0.1
  - 0.2
TEST:
  cv_num: 5
  m: 20
  model: BOMP
  n: 600
  noise_levels:
  - 0.05
  p: 1000
  trial_num: 20
filename: BOMP_600_1000_20_nr_0714.yaml
