MODEL:
  Bag_lst:
  - 1
  - 50
  - 100
  K_lst:
  - 1
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  - 100
  agg_func: weight
  atom_bag_percent:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1
  ignore_warning: true
  random_seed: 1
  replace_flag: false
  select_atom_percent: 0
  signal_bag_percent:
  - 0.6
  - 0.8
  - 1
TEST:
  cv_num: 5
  m: 20
  model: BOMP
  n: 600
  noise_levels:
  - 0.12
  p: 1000
  trial_num: 20
filename: BOMP_600_1000_20_nr_0713.yaml
hydra:
  hydra_logging:
    level: CRITICAL
  job_logging:
    level: CRITICAL
  run:
    dir: memory/0713/
