MODEL:
  Bag_lst:
  - 1
  - 50
  K_lst:
  - 1
  - 10
  - 20
  - 30
  - 40
  agg_func: weight
  atom_bag_percent:
  - 0.5
  - 0.6
  ignore_warning: true
  random_seed: 1
  replace_flag: true
  select_atom_percent: 0
  signal_bag_percent:
  - 0.6
  - 0.8
TEST:
  cv_num: 5
  m: 20
  model: BOMP
  n: 600
  noise_levels:
  - 0.1
  - 0.2
  p: 1000
  trial_num: 2
filename: BOMP_600_1000_20_r_0714.yaml
hydra:
  hydra_logging:
    level: CRITICAL
  job_logging:
    level: CRITICAL
  run:
    dir: memory/0714/
